variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3.8.4-openjdk-17-slim

cache:
  paths:
    - .m2/repository

.artifacts: &artifacts
    artifacts:
      paths:
        - ./target/maven-archiver/*
        - ./target/*.jar
        - ./*pom.xml

verify:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  <<: *artifacts
